// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Thu May 15 21:07:09 2003]
// 
// File        : xmlparams.h
// Class       : XmlReaderParams
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#ifndef __XMLREADERPARAMS_H
#define __XMLREADERPARAMS_H

#include <bfc/dispatch.h>
#include <bfc/common.h>



// ----------------------------------------------------------------------------

class XmlReaderParams: public Dispatchable {
  protected:
    XmlReaderParams() {}
    ~XmlReaderParams() {}
  public:
    const char *getItemName(int i);
    const char *getItemValue(int i);
    const char *getItemValue(const char *name);
    const char *enumItemValues(const char *name, int nb);
    int getItemValueInt(const char *name, int def = 0);
    int getNbItems();
    void addItem(const char *parm, const char *value);
    void removeItem(const char *parm);
    void replaceItem(const char *parm, const char *value);
    int findItem(const char *parm);
  
  protected:
    enum {
      XMLREADERPARAMS_GETITEMNAME = 100,
      XMLREADERPARAMS_GETITEMVALUE = 200,
      XMLREADERPARAMS_GETITEMVALUE2 = 201,
      XMLREADERPARAMS_ENUMITEMVALUES = 202,
      XMLREADERPARAMS_GETITEMVALUEINT = 300,
      XMLREADERPARAMS_GETNBITEMS = 400,
      XMLREADERPARAMS_ADDITEM = 500,
      XMLREADERPARAMS_REMOVEITEM = 600,
      XMLREADERPARAMS_REPLACEITEM = 700,
      XMLREADERPARAMS_FINDITEM = 800,
    };
};

// ----------------------------------------------------------------------------

inline const char *XmlReaderParams::getItemName(int i) {
  const char *__retval = _call(XMLREADERPARAMS_GETITEMNAME, (const char *)0, i);
  return __retval;
}

inline const char *XmlReaderParams::getItemValue(int i) {
  const char *__retval = _call(XMLREADERPARAMS_GETITEMVALUE, (const char *)0, i);
  return __retval;
}

inline const char *XmlReaderParams::getItemValue(const char *name) {
  const char *__retval = _call(XMLREADERPARAMS_GETITEMVALUE2, (const char *)0, name);
  return __retval;
}

inline const char *XmlReaderParams::enumItemValues(const char *name, int nb) {
  const char *__retval = _call(XMLREADERPARAMS_ENUMITEMVALUES, (const char *)0, name, nb);
  return __retval;
}

inline int XmlReaderParams::getItemValueInt(const char *name, int def) {
  int __retval = _call(XMLREADERPARAMS_GETITEMVALUEINT, (int)0, name, def);
  return __retval;
}

inline int XmlReaderParams::getNbItems() {
  int __retval = _call(XMLREADERPARAMS_GETNBITEMS, (int)0);
  return __retval;
}

inline void XmlReaderParams::addItem(const char *parm, const char *value) {
  _voidcall(XMLREADERPARAMS_ADDITEM, parm, value);
}

inline void XmlReaderParams::removeItem(const char *parm) {
  _voidcall(XMLREADERPARAMS_REMOVEITEM, parm);
}

inline void XmlReaderParams::replaceItem(const char *parm, const char *value) {
  _voidcall(XMLREADERPARAMS_REPLACEITEM, parm, value);
}

inline int XmlReaderParams::findItem(const char *parm) {
  int __retval = _call(XMLREADERPARAMS_FINDITEM, (int)0, parm);
  return __retval;
}

// ----------------------------------------------------------------------------

#endif // __XMLREADERPARAMS_H
