// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Thu May 15 21:07:09 2003]
// 
// File        : xmlparams.cpp
// Class       : XmlReaderParams
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#include <precomp.h>
#include "xmlparams.h"


