// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Thu May 15 21:07:09 2003]
// 
// File        : xmlparamsx.h
// Class       : XmlReaderParams
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------

#ifndef __XMLREADERPARAMSX_H
#define __XMLREADERPARAMSX_H

#include "xmlparams.h"




// ----------------------------------------------------------------------------

class COMEXP XmlReaderParamsX : public XmlReaderParams {
  protected:
    XmlReaderParamsX() {}
  public:
    virtual const char *getItemName(int i)=0;
    virtual const char *getItemValue(int i)=0;
    virtual const char *getItemValue2(const char *name);
    virtual const char *enumItemValues(const char *name, int nb)=0;
    virtual int getItemValueInt(const char *name, int def = 0)=0;
    virtual int getNbItems()=0;
    virtual void addItem(const char *parm, const char *value)=0;
    virtual void removeItem(const char *parm)=0;
    virtual void replaceItem(const char *parm, const char *value)=0;
    virtual int findItem(const char *parm)=0;
  
  protected:
    RECVS_DISPATCH;
};

#endif // __XMLREADERPARAMSX_H
