// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Wed Mar 16 17:07:53 2005]
// 
// File        : api_jsX.cpp
// Class       : api_js
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------

#include "api_jsX.h"
#include "api_jsI.h"

#ifdef CBCLASS
#undef CBCLASS
#endif

#define CBCLASS api_jsX
START_DISPATCH;
  VCB(API_JS_ASSIGNFUNCTIONS, assignFunctions);
  CB(API_JS_BOOLTOJSVAL, boolToJSval);
  VCB(API_JS_COLLECTGARBAGE, collectGarbage);
  CB(API_JS_COMPILESCRIPT2, compileScript2);
  CB(API_JS_COMPILESCRIPT, compileScript);
  VCB(API_JS_CREATENAMEDROOT, createNamedRoot);
  CB(API_JS_CREATENEWCONTEXT, createNewContext);
  CB(API_JS_CREATENEWOBJECT, createNewObject);
  CB(API_JS_CREATESCRIPTOBJECT, createScriptObject);
  CB(API_JS_DELETECONTEXT2, deleteContext2);
  CB(API_JS_DELETECONTEXT, deleteContext);
  VCB(API_JS_DELETENAMEDROOT, deleteNamedRoot);
  CB(API_JS_DOUBLETOJSVAL, doubleToJSval);
  CB(API_JS_ENUMCONTEXT, enumContext);
  CB(API_JS_ENUMOBJECT, enumObject);
  CB(API_JS_EVALSCRIPT, evalScript);
  CB(API_JS_EXECUTEFUNCTION, executeFunction);
  CB(API_JS_EXECUTESCRIPT, executeScript);
  CB(API_JS_GETGLOBALOBJECT, getGlobalObject);
  CB(API_JS_GETMAINCONTEXT, getMainContext);
  CB(API_JS_INTTOJSVAL, intToJSval);
  CB(API_JS_JSVALTOBOOL, jsvalToBool);
  CB(API_JS_JSVALTODOUBLE, jsvalToDouble);
  CB(API_JS_JSVALTOINT, jsvalToInt);
  VCB(API_JS_JSVALTOOBJECT, jsvalToObject);
  CB(API_JS_JSVALTOSTRING, jsvalToString);
  CB(API_JS_OBJECTTOJSVAL, objectToJSval);
  CB(API_JS_STRINGTOJSVAL, stringToJSval);
END_DISPATCH;
#undef CBCLASS

JSScript *api_jsX::compileScript2(JSContext *cx, JSObject *obj, const char *bytes, long len, const char *filename) { return static_cast<api_jsI *>(this)->compileScript(cx, obj, bytes, len, filename); }
int api_jsX::deleteContext2(JSContext *ctx) { return static_cast<api_jsI *>(this)->deleteContext(ctx); }
