// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Wed Mar 16 17:07:53 2005]
// 
// File        : api_js.cpp
// Class       : api_js
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#include "api_js.h"


