/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Sat Oct 16 14:54:13 2004]
/*!*/ // 
/*!*/ // File        : api_service.cpp
/*!*/ // Class       : api_service
/*!*/ // class layer : Dispatchable Interface
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
#     include <precomp.h>
#     include "api_service.h"
/*!*/ 
/*!*/ 
