// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/JSGlobalObjectEventSource.cpp
// Class       : JSGlobalObject
// class layer : Event Source for for JSGlobalObject
// ----------------------------------------------------------------------------

#include "precomp.h"
#include "JSGlobalObjectEventSource.h"
#include "JSGlobalObjectEventSink.h"
#include "..\jsglobalobject.h"


