// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/JSGlobalObjectEventSink.h
// Class       : JSGlobalObject
// class layer : Event Sink for JSGlobalObject
// ----------------------------------------------------------------------------

#ifndef JSGLOBALOBJECTEVENTSINK_H
#define JSGLOBALOBJECTEVENTSINK_H

#include <bfc/eventsink.h>
#include "JSGlobalObjectEventSource.h"

class JSTimer;


// ----------------------------------------------------------------------------

class JSGlobalObjectEventSink {
  protected:
    JSGlobalObjectEventSink() {}
    virtual ~JSGlobalObjectEventSink() {
      while (m_sources.getNumItems()>0) {
        eventSink_unregisterTo(m_sources.enumItem(0));
      }
    }
  
  public:
    void eventSink_registerTo(JSGlobalObjectEventSource *eventSource) {
      eventSource->registerJSGlobalObjectEventSink(this);
      m_sources.addItem(eventSource);
    }
    void eventSink_unregisterTo(JSGlobalObjectEventSource *eventSource) {
      eventSource->unregisterJSGlobalObjectEventSink(this);
      m_sources.removeItem(eventSource);
    }
  
  private:
    PtrList<JSGlobalObjectEventSource> m_sources;
};

#endif // JSGLOBALOBJECTEVENTSINK_H
