// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/JSGlobalObjectEventSource.h
// Class       : JSGlobalObject
// class layer : Event Source for JSGlobalObject
// ----------------------------------------------------------------------------

#ifndef JSGLOBALOBJECTEVENTSOURCE_H
#define JSGLOBALOBJECTEVENTSOURCE_H

#include <bfc/eventsource.h>

class JSTimer;

class JSGlobalObjectEventSink;

// ----------------------------------------------------------------------------

class JSGlobalObjectEventSource {
  protected:
    JSGlobalObjectEventSource() {}
    virtual ~JSGlobalObjectEventSource() {}
  
  public:
    
    void registerJSGlobalObjectEventSink(JSGlobalObjectEventSink *sink) { m_sinks.addItem(sink); }
    void unregisterJSGlobalObjectEventSink(JSGlobalObjectEventSink *sink) { m_sinks.removeItem(sink); }
  
  private:
    PtrList<JSGlobalObjectEventSink> m_sinks;
};

#endif // JSGLOBALOBJECTEVENTSOURCE_H
