// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/JSTimerEventSource.h
// Class       : JSTimer
// class layer : Event Source for JSTimer
// ----------------------------------------------------------------------------

#ifndef JSTIMEREVENTSOURCE_H
#define JSTIMEREVENTSOURCE_H

#include <bfc/eventsource.h>


class JSTimerEventSink;

// ----------------------------------------------------------------------------

class JSTimerEventSource {
  protected:
    JSTimerEventSource() {}
    virtual ~JSTimerEventSource() {}
  
  public:
    void eventSource_onTimer();
    
    void registerJSTimerEventSink(JSTimerEventSink *sink) { m_sinks.addItem(sink); }
    void unregisterJSTimerEventSink(JSTimerEventSink *sink) { m_sinks.removeItem(sink); }
  
  private:
    PtrList<JSTimerEventSink> m_sinks;
};

#endif // JSTIMEREVENTSOURCE_H
