// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/JSTimerEventSink.h
// Class       : JSTimer
// class layer : Event Sink for JSTimer
// ----------------------------------------------------------------------------

#ifndef JSTIMEREVENTSINK_H
#define JSTIMEREVENTSINK_H

#include <bfc/eventsink.h>
#include "JSTimerEventSource.h"



// ----------------------------------------------------------------------------

class JSTimerEventSink {
  protected:
    JSTimerEventSink() {}
    virtual ~JSTimerEventSink() {
      while (m_sources.getNumItems()>0) {
        eventSink_unregisterTo(m_sources.enumItem(0));
      }
    }
  
  public:
    void eventSink_registerTo(JSTimerEventSource *eventSource) {
      eventSource->registerJSTimerEventSink(this);
      m_sources.addItem(eventSource);
    }
    void eventSink_unregisterTo(JSTimerEventSource *eventSource) {
      eventSource->unregisterJSTimerEventSink(this);
      m_sources.removeItem(eventSource);
    }
    virtual void eventSink_onTimer(JSTimerEventSource *source) {} 
  
  private:
    PtrList<JSTimerEventSource> m_sources;
};

#endif // JSTIMEREVENTSINK_H
