// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/JSTimerEventSource.cpp
// Class       : JSTimer
// class layer : Event Source for for JSTimer
// ----------------------------------------------------------------------------

#include "precomp.h"
#include "JSTimerEventSource.h"
#include "JSTimerEventSink.h"
#include "../jstimer.h"


void JSTimerEventSource::eventSource_onTimer() {
  foreach(m_sinks)
    m_sinks.getfor()->eventSink_onTimer(this);
  endfor
}

