// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIDndSessionEventSource.h
// Class       : XUIDndSession
// class layer : Event Source for XUIDndSession
// ----------------------------------------------------------------------------

#ifndef XUIDNDSESSIONEVENTSOURCE_H
#define XUIDNDSESSIONEVENTSOURCE_H

#include <bfc/eventsource.h>

class XUIObject;

class XUIDndSessionEventSink;

// ----------------------------------------------------------------------------

class XUIDndSessionEventSource {
  protected:
    XUIDndSessionEventSource() {}
    virtual ~XUIDndSessionEventSource() {}
  
  public:
    void eventSource_onDragEnter(XUIObject *target);
    void eventSource_onDragLeave(XUIObject *target);
    void eventSource_onDragOver(XUIObject *target, int x, int y);
    void eventSource_onDragDrop(XUIObject *target, int x, int y);
    
    void registerXUIDndSessionEventSink(XUIDndSessionEventSink *sink) { m_sinks.addItem(sink); }
    void unregisterXUIDndSessionEventSink(XUIDndSessionEventSink *sink) { m_sinks.removeItem(sink); }
  
  private:
    PtrList<XUIDndSessionEventSink> m_sinks;
};

#endif // XUIDNDSESSIONEVENTSOURCE_H
