// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIDndSessionEventSource.cpp
// Class       : XUIDndSession
// class layer : Event Source for for XUIDndSession
// ----------------------------------------------------------------------------

#include "precomp.h"
#include "XUIDndSessionEventSource.h"
#include "XUIDndSessionEventSink.h"
#include "..\..\xuidndsession.h"


void XUIDndSessionEventSource::eventSource_onDragEnter(XUIObject *target) {
  foreach(m_sinks)
    m_sinks.getfor()->eventSink_onDragEnter(this, target);
  endfor
}

void XUIDndSessionEventSource::eventSource_onDragLeave(XUIObject *target) {
  foreach(m_sinks)
    m_sinks.getfor()->eventSink_onDragLeave(this, target);
  endfor
}

void XUIDndSessionEventSource::eventSource_onDragOver(XUIObject *target, int x, int y) {
  foreach(m_sinks)
    m_sinks.getfor()->eventSink_onDragOver(this, target, x, y);
  endfor
}

void XUIDndSessionEventSource::eventSource_onDragDrop(XUIObject *target, int x, int y) {
  foreach(m_sinks)
    m_sinks.getfor()->eventSink_onDragDrop(this, target, x, y);
  endfor
}

