// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIEditEventSource.h
// Class       : XUIEdit
// class layer : Event Source for XUIEdit
// ----------------------------------------------------------------------------

#ifndef XUIEDITEVENTSOURCE_H
#define XUIEDITEVENTSOURCE_H

#include <bfc/eventsource.h>


class XUIEditEventSink;

// ----------------------------------------------------------------------------

class XUIEditEventSource {
  protected:
    XUIEditEventSource() {}
    virtual ~XUIEditEventSource() {}
  
  public:
    void eventSource_onEdit(const char *value);
    void eventSource_onIdleEdit(const char *value);
    
    void registerXUIEditEventSink(XUIEditEventSink *sink) { m_sinks.addItem(sink); }
    void unregisterXUIEditEventSink(XUIEditEventSink *sink) { m_sinks.removeItem(sink); }
  
  private:
    PtrList<XUIEditEventSink> m_sinks;
};

#endif // XUIEDITEVENTSOURCE_H
