// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIEditEventSource.cpp
// Class       : XUIEdit
// class layer : Event Source for for XUIEdit
// ----------------------------------------------------------------------------

#include "precomp.h"
#include "XUIEditEventSource.h"
#include "XUIEditEventSink.h"
#include "..\xuiedit.h"


void XUIEditEventSource::eventSource_onEdit(const char *value) {
  foreach(m_sinks)
    m_sinks.getfor()->eventSink_onEdit(this, value);
  endfor
}

void XUIEditEventSource::eventSource_onIdleEdit(const char *value) {
  foreach(m_sinks)
    m_sinks.getfor()->eventSink_onIdleEdit(this, value);
  endfor
}

