// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIEditEventSink.h
// Class       : XUIEdit
// class layer : Event Sink for XUIEdit
// ----------------------------------------------------------------------------

#ifndef XUIEDITEVENTSINK_H
#define XUIEDITEVENTSINK_H

#include <bfc/eventsink.h>
#include "XUIEditEventSource.h"



// ----------------------------------------------------------------------------

class XUIEditEventSink {
  protected:
    XUIEditEventSink() {}
    virtual ~XUIEditEventSink() {
      while (m_sources.getNumItems()>0) {
        eventSink_unregisterTo(m_sources.enumItem(0));
      }
    }
  
  public:
    void eventSink_registerTo(XUIEditEventSource *eventSource) {
      eventSource->registerXUIEditEventSink(this);
      m_sources.addItem(eventSource);
    }
    void eventSink_unregisterTo(XUIEditEventSource *eventSource) {
      eventSource->unregisterXUIEditEventSink(this);
      m_sources.removeItem(eventSource);
    }
    virtual void eventSink_onEdit(XUIEditEventSource *source, const char *value) {} 
    virtual void eventSink_onIdleEdit(XUIEditEventSource *source, const char *value) {} 
  
  private:
    PtrList<XUIEditEventSource> m_sources;
};

#endif // XUIEDITEVENTSINK_H
