// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIGroupEventSource.h
// Class       : XUIGroup
// class layer : Event Source for XUIGroup
// ----------------------------------------------------------------------------

#ifndef XUIGROUPEVENTSOURCE_H
#define XUIGROUPEVENTSOURCE_H

#include <bfc/eventsource.h>

class XUIObject;

class XUIGroupEventSink;

// ----------------------------------------------------------------------------

class XUIGroupEventSource {
  protected:
    XUIGroupEventSource() {}
    virtual ~XUIGroupEventSource() {}
  
  public:
    
    void registerXUIGroupEventSink(XUIGroupEventSink *sink) { m_sinks.addItem(sink); }
    void unregisterXUIGroupEventSink(XUIGroupEventSink *sink) { m_sinks.removeItem(sink); }
  
  private:
    PtrList<XUIGroupEventSink> m_sinks;
};

#endif // XUIGROUPEVENTSOURCE_H
