// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIGroupEventSource.cpp
// Class       : XUIGroup
// class layer : Event Source for for XUIGroup
// ----------------------------------------------------------------------------

#include "precomp.h"
#include "XUIGroupEventSource.h"
#include "XUIGroupEventSink.h"
#include "..\xuigroup.h"


