// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIGroupEventSink.h
// Class       : XUIGroup
// class layer : Event Sink for XUIGroup
// ----------------------------------------------------------------------------

#ifndef XUIGROUPEVENTSINK_H
#define XUIGROUPEVENTSINK_H

#include <bfc/eventsink.h>
#include "XUIGroupEventSource.h"

class XUIObject;


// ----------------------------------------------------------------------------

class XUIGroupEventSink {
  protected:
    XUIGroupEventSink() {}
    virtual ~XUIGroupEventSink() {
      while (m_sources.getNumItems()>0) {
        eventSink_unregisterTo(m_sources.enumItem(0));
      }
    }
  
  public:
    void eventSink_registerTo(XUIGroupEventSource *eventSource) {
      eventSource->registerXUIGroupEventSink(this);
      m_sources.addItem(eventSource);
    }
    void eventSink_unregisterTo(XUIGroupEventSource *eventSource) {
      eventSource->unregisterXUIGroupEventSink(this);
      m_sources.removeItem(eventSource);
    }
  
  private:
    PtrList<XUIGroupEventSource> m_sources;
};

#endif // XUIGROUPEVENTSINK_H
