// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUILabelEventSink.h
// Class       : XUILabel
// class layer : Event Sink for XUILabel
// ----------------------------------------------------------------------------

#ifndef XUILABELEVENTSINK_H
#define XUILABELEVENTSINK_H

#include <bfc/eventsink.h>
#include "XUILabelEventSource.h"



// ----------------------------------------------------------------------------

class XUILabelEventSink {
  protected:
    XUILabelEventSink() {}
    virtual ~XUILabelEventSink() {
      while (m_sources.getNumItems()>0) {
        eventSink_unregisterTo(m_sources.enumItem(0));
      }
    }
  
  public:
    void eventSink_registerTo(XUILabelEventSource *eventSource) {
      eventSource->registerXUILabelEventSink(this);
      m_sources.addItem(eventSource);
    }
    void eventSink_unregisterTo(XUILabelEventSource *eventSource) {
      eventSource->unregisterXUILabelEventSink(this);
      m_sources.removeItem(eventSource);
    }
  
  private:
    PtrList<XUILabelEventSource> m_sources;
};

#endif // XUILABELEVENTSINK_H
