// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUILabelEventSource.cpp
// Class       : XUILabel
// class layer : Event Source for for XUILabel
// ----------------------------------------------------------------------------

#include "precomp.h"
#include "XUILabelEventSource.h"
#include "XUILabelEventSink.h"
#include "..\xuilabel.h"


