// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUILabelEventSource.h
// Class       : XUILabel
// class layer : Event Source for XUILabel
// ----------------------------------------------------------------------------

#ifndef XUILABELEVENTSOURCE_H
#define XUILABELEVENTSOURCE_H

#include <bfc/eventsource.h>


class XUILabelEventSink;

// ----------------------------------------------------------------------------

class XUILabelEventSource {
  protected:
    XUILabelEventSource() {}
    virtual ~XUILabelEventSource() {}
  
  public:
    
    void registerXUILabelEventSink(XUILabelEventSink *sink) { m_sinks.addItem(sink); }
    void unregisterXUILabelEventSink(XUILabelEventSink *sink) { m_sinks.removeItem(sink); }
  
  private:
    PtrList<XUILabelEventSink> m_sinks;
};

#endif // XUILABELEVENTSOURCE_H
