// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIOSWindowEventSink.h
// Class       : XUIOSWindow
// class layer : Event Sink for XUIOSWindow
// ----------------------------------------------------------------------------

#ifndef XUIOSWINDOWEVENTSINK_H
#define XUIOSWINDOWEVENTSINK_H

#include <bfc/eventsink.h>
#include "XUIOSWindowEventSource.h"



// ----------------------------------------------------------------------------

class XUIOSWindowEventSink {
  protected:
    XUIOSWindowEventSink() {}
    virtual ~XUIOSWindowEventSink() {
      while (m_sources.getNumItems()>0) {
        eventSink_unregisterTo(m_sources.enumItem(0));
      }
    }
  
  public:
    void eventSink_registerTo(XUIOSWindowEventSource *eventSource) {
      eventSource->registerXUIOSWindowEventSink(this);
      m_sources.addItem(eventSource);
    }
    void eventSink_unregisterTo(XUIOSWindowEventSource *eventSource) {
      eventSource->unregisterXUIOSWindowEventSink(this);
      m_sources.removeItem(eventSource);
    }
    virtual void eventSink_onUserClose(XUIOSWindowEventSource *source) {} 
  
  private:
    PtrList<XUIOSWindowEventSource> m_sources;
};

#endif // XUIOSWINDOWEVENTSINK_H
