// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIOSWindowEventSource.h
// Class       : XUIOSWindow
// class layer : Event Source for XUIOSWindow
// ----------------------------------------------------------------------------

#ifndef XUIOSWINDOWEVENTSOURCE_H
#define XUIOSWINDOWEVENTSOURCE_H

#include <bfc/eventsource.h>


class XUIOSWindowEventSink;

// ----------------------------------------------------------------------------

class XUIOSWindowEventSource {
  protected:
    XUIOSWindowEventSource() {}
    virtual ~XUIOSWindowEventSource() {}
  
  public:
    void eventSource_onUserClose();
    
    void registerXUIOSWindowEventSink(XUIOSWindowEventSink *sink) { m_sinks.addItem(sink); }
    void unregisterXUIOSWindowEventSink(XUIOSWindowEventSink *sink) { m_sinks.removeItem(sink); }
  
  private:
    PtrList<XUIOSWindowEventSink> m_sinks;
};

#endif // XUIOSWINDOWEVENTSOURCE_H
