// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIWindowEventSource.h
// Class       : XUIWindow
// class layer : Event Source for XUIWindow
// ----------------------------------------------------------------------------

#ifndef XUIWINDOWEVENTSOURCE_H
#define XUIWINDOWEVENTSOURCE_H

#include <bfc/eventsource.h>


class XUIWindowEventSink;

// ----------------------------------------------------------------------------

class XUIWindowEventSource {
  protected:
    XUIWindowEventSource() {}
    virtual ~XUIWindowEventSource() {}
  
  public:
    
    void registerXUIWindowEventSink(XUIWindowEventSink *sink) { m_sinks.addItem(sink); }
    void unregisterXUIWindowEventSink(XUIWindowEventSink *sink) { m_sinks.removeItem(sink); }
  
  private:
    PtrList<XUIWindowEventSink> m_sinks;
};

#endif // XUIWINDOWEVENTSOURCE_H
