// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIWindowEventSink.h
// Class       : XUIWindow
// class layer : Event Sink for XUIWindow
// ----------------------------------------------------------------------------

#ifndef XUIWINDOWEVENTSINK_H
#define XUIWINDOWEVENTSINK_H

#include <bfc/eventsink.h>
#include "XUIWindowEventSource.h"



// ----------------------------------------------------------------------------

class XUIWindowEventSink {
  protected:
    XUIWindowEventSink() {}
    virtual ~XUIWindowEventSink() {
      while (m_sources.getNumItems()>0) {
        eventSink_unregisterTo(m_sources.enumItem(0));
      }
    }
  
  public:
    void eventSink_registerTo(XUIWindowEventSource *eventSource) {
      eventSource->registerXUIWindowEventSink(this);
      m_sources.addItem(eventSource);
    }
    void eventSink_unregisterTo(XUIWindowEventSource *eventSource) {
      eventSource->unregisterXUIWindowEventSink(this);
      m_sources.removeItem(eventSource);
    }
  
  private:
    PtrList<XUIWindowEventSource> m_sources;
};

#endif // XUIWINDOWEVENTSINK_H
