// ----------------------------------------------------------------------------
// Generated by SourceSink Factory - DO NOT EDIT
// 
// File        : ../sourcesink/XUIWindowEventSource.cpp
// Class       : XUIWindow
// class layer : Event Source for for XUIWindow
// ----------------------------------------------------------------------------

#include "precomp.h"
#include "XUIWindowEventSource.h"
#include "XUIWindowEventSink.h"
#include "..\xuiwindow.h"


