/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Mon Jul 14 23:40:32 2008]
/*!*/ // 
/*!*/ // File        : api_locales.h
/*!*/ // Class       : api_locales
/*!*/ // class layer : Dispatchable Interface
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
#ifndef __API_LOCALES_H
#define __API_LOCALES_H
/*!*/ 
#include "bfc/dispatch.h"
/*!*/ 
/*!*/ 
/*!*/ 
/*!*/ 
#include <wnd/rootwnd.h>
/*!*/ 
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
/*!*/ class COMEXP api_locales: public Dispatchable {
/*!*/   protected:
/*!*/     api_locales() {}
/*!*/     ~api_locales() {}
/*!*/   public:
/*!*/     void locales_addTranslation(const char *from, const char *to);
/*!*/     const char *locales_getTranslation(const char *from);
/*!*/     int locales_getNumEntries();
/*!*/     const char *locales_enumEntry(int n);
/*!*/     const char *locales_getBindFromAction(int action);
/*!*/     void locales_registerAcceleratorSection(const char *name, RootWnd *wnd, int global = 0);
/*!*/   
/*!*/   protected:
/*!*/     enum {
/*!*/       API_LOCALES_LOCALES_ADDTRANSLATION = 10,
/*!*/       API_LOCALES_LOCALES_GETTRANSLATION = 20,
/*!*/       API_LOCALES_LOCALES_GETNUMENTRIES = 30,
/*!*/       API_LOCALES_LOCALES_ENUMENTRY = 40,
/*!*/       API_LOCALES_LOCALES_GETBINDFROMACTION = 50,
/*!*/       API_LOCALES_LOCALES_REGISTERACCELERATORSECTION = 60,
/*!*/     };
/*!*/ };
/*!*/ 
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
/*!*/ inline void api_locales::locales_addTranslation(const char *from, const char *to) {
/*!*/   _voidcall(API_LOCALES_LOCALES_ADDTRANSLATION, from, to);
/*!*/ }
/*!*/ 
/*!*/ inline const char *api_locales::locales_getTranslation(const char *from) {
/*!*/   const char *__retval = _call(API_LOCALES_LOCALES_GETTRANSLATION, (const char *)0, from);
/*!*/   return __retval;
/*!*/ }
/*!*/ 
/*!*/ inline int api_locales::locales_getNumEntries() {
/*!*/   int __retval = _call(API_LOCALES_LOCALES_GETNUMENTRIES, (int)0);
/*!*/   return __retval;
/*!*/ }
/*!*/ 
/*!*/ inline const char *api_locales::locales_enumEntry(int n) {
/*!*/   const char *__retval = _call(API_LOCALES_LOCALES_ENUMENTRY, (const char *)0, n);
/*!*/   return __retval;
/*!*/ }
/*!*/ 
/*!*/ inline const char *api_locales::locales_getBindFromAction(int action) {
/*!*/   const char *__retval = _call(API_LOCALES_LOCALES_GETBINDFROMACTION, (const char *)0, action);
/*!*/   return __retval;
/*!*/ }
/*!*/ 
/*!*/ inline void api_locales::locales_registerAcceleratorSection(const char *name, RootWnd *wnd, int global) {
/*!*/   _voidcall(API_LOCALES_LOCALES_REGISTERACCELERATORSECTION, name, wnd, global);
/*!*/ }
/*!*/ 
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
/*!*/ 
/*!*/ // {0928554A-72FA-438a-B5A8-CEE1115A8032}
/*!*/ static const GUID localesGuid = 
/*!*/ { 0x928554a, 0x72fa, 0x438a, { 0xb5, 0xa8, 0xce, 0xe1, 0x11, 0x5a, 0x80, 0x32 } };
/*!*/ 
/*!*/ extern api_locales *localeApi;
/*!*/ 
/*!*/ 
#endif // __API_LOCALES_H
