/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Mon Jul 14 23:40:32 2008]
/*!*/ // 
/*!*/ // File        : api_locales.cpp
/*!*/ // Class       : api_locales
/*!*/ // class layer : Dispatchable Interface
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
#include "precomp.h"
#include "api_locales.h"
/*!*/ 
/*!*/ 
