/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Mon Jul 14 23:40:32 2008]
/*!*/ // 
/*!*/ // File        : api_localesX.h
/*!*/ // Class       : api_locales
/*!*/ // class layer : Dispatchable Receiver
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
#ifndef __API_LOCALESX_H
#define __API_LOCALESX_H
/*!*/ 
#include "api_locales.h"
/*!*/ 
/*!*/ 
/*!*/ 
/*!*/ 
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
/*!*/ class COMEXP api_localesX : public api_locales {
/*!*/   protected:
/*!*/     api_localesX() {}
/*!*/   public:
/*!*/     virtual void locales_addTranslation(const char *from, const char *to)=0;
/*!*/     virtual const char *locales_getTranslation(const char *from)=0;
/*!*/     virtual int locales_getNumEntries()=0;
/*!*/     virtual const char *locales_enumEntry(int n)=0;
/*!*/     virtual const char *locales_getBindFromAction(int action)=0;
/*!*/     virtual void locales_registerAcceleratorSection(const char *name, RootWnd *wnd, int global = 0)=0;
/*!*/   
/*!*/   protected:
/*!*/     RECVS_DISPATCH;
/*!*/ };
/*!*/ 
#endif // __API_LOCALESX_H
