/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Mon Jul 14 23:40:32 2008]
/*!*/ // 
/*!*/ // File        : api_localesX.cpp
/*!*/ // Class       : api_locales
/*!*/ // class layer : Dispatchable Receiver
/*!*/ // ----------------------------------------------------------------------------
#include "precomp.h"
/*!*/ 
#include "api_localesX.h"
#include "api_localesI.h"
/*!*/ 
#ifdef CBCLASS
#undef CBCLASS
#endif
/*!*/ 
#define CBCLASS api_localesX
/*!*/ START_DISPATCH;
/*!*/   VCB(API_LOCALES_LOCALES_ADDTRANSLATION, locales_addTranslation);
/*!*/   CB(API_LOCALES_LOCALES_GETTRANSLATION, locales_getTranslation);
/*!*/   CB(API_LOCALES_LOCALES_GETNUMENTRIES, locales_getNumEntries);
/*!*/   CB(API_LOCALES_LOCALES_ENUMENTRY, locales_enumEntry);
/*!*/   CB(API_LOCALES_LOCALES_GETBINDFROMACTION, locales_getBindFromAction);
/*!*/   VCB(API_LOCALES_LOCALES_REGISTERACCELERATORSECTION, locales_registerAcceleratorSection);
/*!*/ END_DISPATCH;
#undef CBCLASS
/*!*/ 
