/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Sun Jan 08 14:25:49 2012]
/*!*/ // 
/*!*/ // File        : api_memmgrx.h
/*!*/ // Class       : api_memmgr
/*!*/ // class layer : Dispatchable Receiver
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
#ifndef __API_MEMMGRX_H
#define __API_MEMMGRX_H
/*!*/ 
#include "api_memmgr.h"
/*!*/ 
/*!*/ 
/*!*/ 
/*!*/ 
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
/*!*/ class COMEXP api_memmgrX : public api_memmgr {
/*!*/   protected:
/*!*/     api_memmgrX() {}
/*!*/   public:
/*!*/     virtual void *sysMalloc(unsigned int size)=0;
/*!*/     virtual void sysFree(void *ptr)=0;
/*!*/     virtual void *sysReAlloc(void *ptr, unsigned int size)=0;
/*!*/     virtual void *sysMemSet(void *ptr, int val, int size)=0;
/*!*/     virtual void *sysMemZero(void *ptr, int size)=0;
/*!*/   
/*!*/   protected:
/*!*/     RECVS_DISPATCH;
/*!*/ };
/*!*/ 
#endif // __API_MEMMGRX_H
