/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Sun Jan 08 14:25:49 2012]
/*!*/ // 
/*!*/ // File        : api_memmgr.h
/*!*/ // Class       : api_memmgr
/*!*/ // class layer : Dispatchable Interface
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
#ifndef __API_MEMMGR_H
#define __API_MEMMGR_H
/*!*/ 
#include "bfc/dispatch.h"
/*!*/ 
/*!*/ 
/*!*/ 
/*!*/ 
/*!*/ 
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
/*!*/ class COMEXP api_memmgr: public Dispatchable {
/*!*/   protected:
/*!*/     api_memmgr() {}
/*!*/     ~api_memmgr() {}
/*!*/   public:
/*!*/     void *sysMalloc(unsigned int size);
/*!*/     void sysFree(void *ptr);
/*!*/     void *sysReAlloc(void *ptr, unsigned int size);
/*!*/     void *sysMemSet(void *ptr, int val, int size);
/*!*/     void *sysMemZero(void *ptr, int size);
/*!*/   
/*!*/   protected:
/*!*/     enum {
/*!*/       API_MEMMGR_SYSMALLOC = 10,
/*!*/       API_MEMMGR_SYSFREE = 20,
/*!*/       API_MEMMGR_SYSREALLOC = 30,
/*!*/       API_MEMMGR_SYSMEMSET = 40,
/*!*/       API_MEMMGR_SYSMEMZERO = 50,
/*!*/     };
/*!*/ };
/*!*/ 
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
/*!*/ inline void *api_memmgr::sysMalloc(unsigned int size) {
/*!*/   void *__retval = _call(API_MEMMGR_SYSMALLOC, (void *)NULL, size);
/*!*/   return __retval;
/*!*/ }
/*!*/ 
/*!*/ inline void api_memmgr::sysFree(void *ptr) {
/*!*/   _voidcall(API_MEMMGR_SYSFREE, ptr);
/*!*/ }
/*!*/ 
/*!*/ inline void *api_memmgr::sysReAlloc(void *ptr, unsigned int size) {
/*!*/   void *__retval = _call(API_MEMMGR_SYSREALLOC, (void *)NULL, ptr, size);
/*!*/   return __retval;
/*!*/ }
/*!*/ 
/*!*/ inline void *api_memmgr::sysMemSet(void *ptr, int val, int size) {
/*!*/   void *__retval = _call(API_MEMMGR_SYSMEMSET, (void *)NULL, ptr, val, size);
/*!*/   return __retval;
/*!*/ }
/*!*/ 
/*!*/ inline void *api_memmgr::sysMemZero(void *ptr, int size) {
/*!*/   void *__retval = _call(API_MEMMGR_SYSMEMZERO, (void *)NULL, ptr, size);
/*!*/   return __retval;
/*!*/ }
/*!*/ 
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
/*!*/ 
/*!*/ // {0EED260E-C428-4c19-A152-F75F190E0B07}
/*!*/ static const GUID memmgrApiServiceGuid= 
/*!*/ { 0xeed260e, 0xc428, 0x4c19, { 0xa1, 0x52, 0xf7, 0x5f, 0x19, 0xe, 0xb, 0x7 } };
/*!*/ 
/*!*/ extern api_memmgr *memmgrApi;
/*!*/ 
#endif // __API_MEMMGR_H
