/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Sun Jan 08 14:25:49 2012]
/*!*/ // 
/*!*/ // File        : api_memmgr.cpp
/*!*/ // Class       : api_memmgr
/*!*/ // class layer : Dispatchable Interface
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
#include "precomp.h"
#include "api_memmgr.h"
/*!*/ 
/*!*/ 
