// ----------------------------------------------------------------------------
// Generated by JSScriptable Factory - DO NOT EDIT
// 
// File        : ../js/JSXUILabel.cpp
// Class       : XUILabel
// class layer : Javascript Dispatcher
// ----------------------------------------------------------------------------

#include "precomp.h"
#include "JSXUILabel.h"
#include "..\xuilabel.h"


#pragma warning(push)
#pragma warning(disable: 4800)


JSXUILabel::JSXUILabel() {
  XUILabel *pthis = (static_cast<XUILabel *>(this));
  pthis->js_addInterface(JS_XUILabel_GUID, pthis);
  pthis->js_addClassDescriptor(&JSXUILabel::classDescriptor);
  pthis->js_addFunctionTable(JSXUILabel::functionTable);
  jsSink = new JSXUILabelEventSink(this);
  jsSink->eventSink_registerTo(pthis);
}

JSXUILabel::~JSXUILabel() {
  delete jsSink;
}

JSClass JSXUILabel::classDescriptor = {
  "XUILabel", JSCLASS_HAS_PRIVATE,
  JS_PropertyStub, JS_PropertyStub, JS_PropertyStub, JS_PropertyStub,
  JS_EnumerateStub, JS_ResolveStub, JS_ConvertStub, JS_FinalizeStub,
  JSCLASS_NO_OPTIONAL_MEMBERS
};

JSFunctionSpec JSXUILabel::functionTable[] = {
  {0,0,0,0,0},
};

// ----------------------------------------------------------------------------


