// ----------------------------------------------------------------------------
// Generated by JSScriptable Factory - DO NOT EDIT
// 
// File        : ../js/JSXUIWindow.cpp
// Class       : XUIWindow
// class layer : Javascript Dispatcher
// ----------------------------------------------------------------------------

#include "precomp.h"
#include "JSXUIWindow.h"
#include "..\xuiwindow.h"


#pragma warning(push)
#pragma warning(disable: 4800)


JSXUIWindow::JSXUIWindow() {
  XUIWindow *pthis = (static_cast<XUIWindow *>(this));
  pthis->js_addInterface(JS_XUIWindow_GUID, pthis);
  pthis->js_addClassDescriptor(&JSXUIWindow::classDescriptor);
  pthis->js_addFunctionTable(JSXUIWindow::functionTable);
  jsSink = new JSXUIWindowEventSink(this);
  jsSink->eventSink_registerTo(pthis);
}

JSXUIWindow::~JSXUIWindow() {
  delete jsSink;
}

JSClass JSXUIWindow::classDescriptor = {
  "XUIWindow", JSCLASS_HAS_PRIVATE,
  JS_PropertyStub, JS_PropertyStub, JS_PropertyStub, JS_PropertyStub,
  JS_EnumerateStub, JS_ResolveStub, JS_ConvertStub, JS_FinalizeStub,
  JSCLASS_NO_OPTIONAL_MEMBERS
};

JSFunctionSpec JSXUIWindow::functionTable[] = {
  {0,0,0,0,0},
};

// ----------------------------------------------------------------------------


