// ----------------------------------------------------------------------------
// Generated by JSScriptable Factory - DO NOT EDIT
// 
// File        : ../js/JSXUILabel.h
// Class       : XUILabel
// class layer : Javascript Dispatcher
// ----------------------------------------------------------------------------

#ifndef JSXUILABEL_H
#define JSXUILABEL_H

#include <api/js/jsscriptable.h>
#include "../sourcesink/XUILabelEventSink.h"
#include <api/js/jseventlistener.h>



const GUID JS_XUILabel_GUID = { 0xa730fb29, 0x6066, 0x4620, { 0xaf, 0x85, 0xe3, 0x73, 0x92, 0x53, 0x2c, 0x7f } };

class JSXUILabelEventSink;
// ----------------------------------------------------------------------------

class JSXUILabel {
  protected:
    JSXUILabel();
    virtual ~JSXUILabel();
  
  public:
    static JSClass JSXUILabel::classDescriptor;
    static JSFunctionSpec JSXUILabel::functionTable[];
    
  public:
  
  
  private:
    JSXUILabelEventSink *jsSink;
};

// ----------------------------------------------------------------------------

class JSXUILabelEventSink : public XUILabelEventSink {
  public:
    JSXUILabelEventSink(JSXUILabel *jsclass) : m_jsClass(jsclass) {}
    virtual ~JSXUILabelEventSink() {}
  private:
    JSXUILabel *m_jsClass;
};

#endif // JSXUILABEL_H
