// ----------------------------------------------------------------------------
// Generated by JSScriptable Factory - DO NOT EDIT
// 
// File        : ../js/JSXUIEdit.h
// Class       : XUIEdit
// class layer : Javascript Dispatcher
// ----------------------------------------------------------------------------

#ifndef JSXUIEDIT_H
#define JSXUIEDIT_H

#include <api/js/jsscriptable.h>
#include "../sourcesink/XUIEditEventSink.h"
#include <api/js/jseventlistener.h>



const GUID JS_XUIEdit_GUID = { 0x094f3007, 0x5e48, 0x4754, { 0x9d, 0xdb, 0xda, 0x7d, 0x57, 0xc4, 0x87, 0x0c } };

class JSXUIEditEventSink;
// ----------------------------------------------------------------------------

class JSXUIEdit {
  protected:
    JSXUIEdit();
    virtual ~JSXUIEdit();
  
  public:
    static JSClass JSXUIEdit::classDescriptor;
    static JSFunctionSpec JSXUIEdit::functionTable[];
    
  public:
    static JSBool fromjs_selectAll(JSContext *cx, JSObject *obj, uintN argc, jsval *argv, jsval *rval);
  
    void tojs_onEdit(const char *value);
    void tojs_onIdleEdit(const char *value);
  
  private:
    JSXUIEditEventSink *jsSink;
};

// ----------------------------------------------------------------------------

class JSXUIEditEventSink : public XUIEditEventSink {
  public:
    JSXUIEditEventSink(JSXUIEdit *jsclass) : m_jsClass(jsclass) {}
    virtual ~JSXUIEditEventSink() {}
    virtual void eventSink_onEdit(XUIEditEventSource *source, const char *value);
    virtual void eventSink_onIdleEdit(XUIEditEventSource *source, const char *value);
  private:
    JSXUIEdit *m_jsClass;
};

#endif // JSXUIEDIT_H
