// ----------------------------------------------------------------------------
// Generated by JSScriptable Factory - DO NOT EDIT
// 
// File        : ../js/JSXUIOSWindow.h
// Class       : XUIOSWindow
// class layer : Javascript Dispatcher
// ----------------------------------------------------------------------------

#ifndef JSXUIOSWINDOW_H
#define JSXUIOSWINDOW_H

#include <api/js/jsscriptable.h>
#include "../sourcesink/XUIOSWindowEventSink.h"
#include <api/js/jseventlistener.h>



const GUID JS_XUIOSWindow_GUID = { 0x6d18d2a8, 0xd414, 0x4163, { 0xad, 0x15, 0xbc, 0xcc, 0x5e, 0x65, 0xa3, 0xb6 } };

class JSXUIOSWindowEventSink;
// ----------------------------------------------------------------------------

class JSXUIOSWindow {
  protected:
    JSXUIOSWindow();
    virtual ~JSXUIOSWindow();
  
  public:
    static JSClass JSXUIOSWindow::classDescriptor;
    static JSFunctionSpec JSXUIOSWindow::functionTable[];
    
  public:
  
    void tojs_onUserClose();
  
  private:
    JSXUIOSWindowEventSink *jsSink;
};

// ----------------------------------------------------------------------------

class JSXUIOSWindowEventSink : public XUIOSWindowEventSink {
  public:
    JSXUIOSWindowEventSink(JSXUIOSWindow *jsclass) : m_jsClass(jsclass) {}
    virtual ~JSXUIOSWindowEventSink() {}
    virtual void eventSink_onUserClose(XUIOSWindowEventSource *source);
  private:
    JSXUIOSWindow *m_jsClass;
};

#endif // JSXUIOSWINDOW_H
