#ifndef EVENTSOURCE_H
#define EVENTSOURCE_H

// This base class is the ancestor of classes generated by the SourceSink.xpst XPP template

class EventSink;

class EventSource {
protected:
  EventSource() {}
  virtual ~EventSource() {};

public:
  void eventSource_registerSink(EventSink *sink) { m_sinks.addItem(sink); }
  void eventSource_unregisterSink(EventSink *sink) { m_sinks.removeItem(sink); }
  int eventSource_getNumSinks() { return m_sinks.getNumItems(); }
  EventSink *eventSource_enumSink(int i) { return m_sinks.enumItem(i); }

protected:
  PtrList<EventSink> m_sinks;
};

#endif
