/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Sun May 30 10:47:30 2010]
/*!*/ // 
/*!*/ // File        : api_filereaderx.cpp
/*!*/ // Class       : api_filereader
/*!*/ // class layer : Dispatchable Receiver
/*!*/ // ----------------------------------------------------------------------------
#include "precomp.h"
/*!*/ 
#include "api_filereaderx.h"
#include "api_filereaderI.h"
/*!*/ 
#ifdef CBCLASS
#undef CBCLASS
#endif
/*!*/ 
#define CBCLASS api_filereaderX
/*!*/ START_DISPATCH;
/*!*/   CB(API_FILEREADER_FILECANOPEN, fileCanOpen);
/*!*/   CB(API_FILEREADER_FILEOPEN, fileOpen);
/*!*/   VCB(API_FILEREADER_FILECLOSE, fileClose);
/*!*/   CB(API_FILEREADER_FILEREAD, fileRead);
/*!*/   CB(API_FILEREADER_FILEWRITE, fileWrite);
/*!*/   CB(API_FILEREADER_FILECANSEEK, fileCanSeek);
/*!*/   CB(API_FILEREADER_FILESEEK, fileSeek);
/*!*/   CB(API_FILEREADER_FILEEXISTS, fileExists);
/*!*/   CB(API_FILEREADER_FILEISDIRECTORY, fileIsDirectory);
/*!*/ END_DISPATCH;
#undef CBCLASS
/*!*/ 
