/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Sun May 30 10:47:30 2010]
/*!*/ // 
/*!*/ // File        : api_filereaderx.h
/*!*/ // Class       : api_filereader
/*!*/ // class layer : Dispatchable Receiver
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
#ifndef __API_FILEREADERX_H
#define __API_FILEREADERX_H
/*!*/ 
#include "api_filereader.h"
/*!*/ 
/*!*/ 
/*!*/ 
/*!*/ 
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
/*!*/ class COMEXP api_filereaderX : public api_filereader {
/*!*/   protected:
/*!*/     api_filereaderX() {}
/*!*/   public:
/*!*/     virtual int fileCanOpen(const char *filename, int mode)=0;
/*!*/     virtual void *fileOpen(const char *filename, int mode)=0;
/*!*/     virtual void fileClose(void *file)=0;
/*!*/     virtual int fileRead(void *file, char *buf, int len)=0;
/*!*/     virtual int fileWrite(void *file, char *buf, int len)=0;
/*!*/     virtual int fileCanSeek(void *file)=0;
/*!*/     virtual int fileSeek(void *file, int start, int dist)=0;
/*!*/     virtual int fileExists(const char *filename)=0;
/*!*/     virtual int fileIsDirectory(const char *filename)=0;
/*!*/   
/*!*/   protected:
/*!*/     RECVS_DISPATCH;
/*!*/ };
/*!*/ 
#endif // __API_FILEREADERX_H
