/*!*/ // ----------------------------------------------------------------------------
/*!*/ // Generated by InterfaceFactory [Sun May 30 10:47:30 2010]
/*!*/ // 
/*!*/ // File        : api_filereader.cpp
/*!*/ // Class       : api_filereader
/*!*/ // class layer : Dispatchable Interface
/*!*/ // ----------------------------------------------------------------------------
/*!*/ 
#include "precomp.h"
#include "api_filereader.h"
/*!*/ 
/*!*/ 
