/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#include "../../../studio/api.h"
#include "c_browser.h"
#include "../objcontroller.h"

C_Browser::C_Browser(ScriptObject *object) : C_GuiObject(object) {
  inited = 0;
  C_hook(object);
}

C_Browser::C_Browser() {
  inited = 0;
}

void C_Browser::C_hook(ScriptObject *object) {
  ASSERT(!inited);
  ScriptObjectController *controller = object->vcpu_getController();
  obj = controller->cast(object, browserGuid);
  if (obj != object && obj != NULL)
    controller = obj->vcpu_getController();
  else
    obj = NULL;

  if (!loaded) {
    loaded = 1;
    navigateurl_id = api->maki_addDlfRef(controller, "navigateUrl", this);
    back_id = api->maki_addDlfRef(controller, "back", this);
    forward_id = api->maki_addDlfRef(controller, "forward", this);
    stop_id = api->maki_addDlfRef(controller, "stop", this);
    refresh_id = api->maki_addDlfRef(controller, "refresh", this);
    home_id = api->maki_addDlfRef(controller, "home", this);
    settargetname_id = api->maki_addDlfRef(controller, "setTargetName", this);
    onbeforenavigate_id = api->maki_addDlfRef(controller, "onBeforeNavigate", this);
    ondocumentcomplete_id = api->maki_addDlfRef(controller, "onDocumentComplete", this);
  }
  inited = 1;
}

C_Browser::~C_Browser() {
}

ScriptObject *C_Browser::getScriptObject() {
  if (obj != NULL) return obj;
  return C_BROWSER_PARENT::getScriptObject();
}

void C_Browser::navigateUrl(const char *url) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_STRING(url);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), navigateurl_id, params);
}

void C_Browser::back() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), back_id, NULL);
}

void C_Browser::forward() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), forward_id, NULL);
}

void C_Browser::stop() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), stop_id, NULL);
}

void C_Browser::refresh() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), refresh_id, NULL);
}

void C_Browser::home() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), home_id, NULL);
}

void C_Browser::setTargetName(const char *targetname) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_STRING(targetname);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), settargetname_id, params);
}

int C_Browser::onBeforeNavigate(const char *url, int flags, const char *targetframename) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_STRING(url);
  scriptVar b = MAKE_SCRIPT_INT(flags);
  scriptVar c = MAKE_SCRIPT_STRING(targetframename);
  scriptVar *params[3] = {&a, &b, &c};
  return GET_SCRIPT_INT(api->maki_callFunction(getScriptObject(), onbeforenavigate_id, params));
}

void C_Browser::onDocumentComplete(const char *url) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_STRING(url);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), ondocumentcomplete_id, params);
}

int C_Browser::loaded=0;
int C_Browser::navigateurl_id=0;
int C_Browser::back_id=0;
int C_Browser::forward_id=0;
int C_Browser::stop_id=0;
int C_Browser::refresh_id=0;
int C_Browser::home_id=0;
int C_Browser::settargetname_id=0;
int C_Browser::onbeforenavigate_id=0;
int C_Browser::ondocumentcomplete_id=0;
