/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#include "../../../studio/api.h"
#include "c_button.h"
#include "../objcontroller.h"

C_Button::C_Button(ScriptObject *object) : C_GuiObject(object) {
  inited = 0;
  C_hook(object);
}

C_Button::C_Button() {
  inited = 0;
}

void C_Button::C_hook(ScriptObject *object) {
  ASSERT(!inited);
  ScriptObjectController *controller = object->vcpu_getController();
  obj = controller->cast(object, buttonGuid);
  if (obj != object && obj != NULL)
    controller = obj->vcpu_getController();
  else
    obj = NULL;

  if (!loaded) {
    loaded = 1;
    onactivate_id = api->maki_addDlfRef(controller, "onActivate", this);
    onleftclick_id = api->maki_addDlfRef(controller, "onLeftClick", this);
    onrightclick_id = api->maki_addDlfRef(controller, "onRightClick", this);
    setactivated_id = api->maki_addDlfRef(controller, "setActivated", this);
    setactivatednocallback_id = api->maki_addDlfRef(controller, "setActivatedNoCallback", this);
    getactivated_id = api->maki_addDlfRef(controller, "getActivated", this);
    leftclick_id = api->maki_addDlfRef(controller, "leftClick", this);
    rightclick_id = api->maki_addDlfRef(controller, "rightClick", this);
  }
  inited = 1;
}

C_Button::~C_Button() {
}

ScriptObject *C_Button::getScriptObject() {
  if (obj != NULL) return obj;
  return C_BUTTON_PARENT::getScriptObject();
}

void C_Button::onActivate(int activated) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_INT(activated);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), onactivate_id, params);
}

void C_Button::onLeftClick() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), onleftclick_id, NULL);
}

void C_Button::onRightClick() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), onrightclick_id, NULL);
}

void C_Button::setActivated(int onoff) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_INT(onoff);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), setactivated_id, params);
}

void C_Button::setActivatedNoCallback(int onoff) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_INT(onoff);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), setactivatednocallback_id, params);
}

int C_Button::getActivated() {
  ASSERT(inited);
  return GET_SCRIPT_INT(api->maki_callFunction(getScriptObject(), getactivated_id, NULL));
}

void C_Button::leftClick() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), leftclick_id, NULL);
}

void C_Button::rightClick() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), rightclick_id, NULL);
}

int C_Button::loaded=0;
int C_Button::onactivate_id=0;
int C_Button::onleftclick_id=0;
int C_Button::onrightclick_id=0;
int C_Button::setactivated_id=0;
int C_Button::setactivatednocallback_id=0;
int C_Button::getactivated_id=0;
int C_Button::leftclick_id=0;
int C_Button::rightclick_id=0;
