/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __C_BUTTON_H
#define __C_BUTTON_H

#include "c_guiobject.h"

#define C_BUTTON_PARENT C_GuiObject

class COMEXP C_Button : public C_BUTTON_PARENT {
  public:

  C_Button(ScriptObject *object);
  C_Button();
  virtual ~C_Button();

  virtual void C_hook(ScriptObject *o);

  ScriptObject *getScriptObject();

  virtual void onActivate(int activated);
  virtual void onLeftClick();
  virtual void onRightClick();
  virtual void setActivated(int onoff);
  virtual void setActivatedNoCallback(int onoff);
  virtual int getActivated();
  virtual void leftClick();
  virtual void rightClick();

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int onactivate_id;
  static int onleftclick_id;
  static int onrightclick_id;
  static int setactivated_id;
  static int setactivatednocallback_id;
  static int getactivated_id;
  static int leftclick_id;
  static int rightclick_id;
};

#endif
