/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#include "../../../studio/api.h"
#include "c_container.h"
#include "../objcontroller.h"

C_Container::C_Container(ScriptObject *object) : C_RootObject(object) {
  inited = 0;
  C_hook(object);
}

C_Container::C_Container() {
  inited = 0;
}

void C_Container::C_hook(ScriptObject *object) {
  ASSERT(!inited);
  ScriptObjectController *controller = object->vcpu_getController();
  obj = controller->cast(object, containerGuid);
  if (obj != object && obj != NULL)
    controller = obj->vcpu_getController();
  else
    obj = NULL;

  if (!loaded) {
    loaded = 1;
    onswitchtolayout_id = api->maki_addDlfRef(controller, "onSwitchToLayout", this);
    onhidelayout_id = api->maki_addDlfRef(controller, "onHideLayout", this);
    onshowlayout_id = api->maki_addDlfRef(controller, "onShowLayout", this);
    getlayout_id = api->maki_addDlfRef(controller, "getLayout", this);
    getnumlayouts_id = api->maki_addDlfRef(controller, "getNumLayouts", this);
    enumlayout_id = api->maki_addDlfRef(controller, "enumLayout", this);
    switchtolayout_id = api->maki_addDlfRef(controller, "switchToLayout", this);
    show_id = api->maki_addDlfRef(controller, "show", this);
    hide_id = api->maki_addDlfRef(controller, "hide", this);
    toggle_id = api->maki_addDlfRef(controller, "toggle", this);
    isdynamic_id = api->maki_addDlfRef(controller, "isDynamic", this);
    setname_id = api->maki_addDlfRef(controller, "setName", this);
  }
  inited = 1;
}

C_Container::~C_Container() {
}

ScriptObject *C_Container::getScriptObject() {
  if (obj != NULL) return obj;
  return C_CONTAINER_PARENT::getScriptObject();
}

void C_Container::onSwitchToLayout(ScriptObject *newlayout) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_OBJECT(newlayout);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), onswitchtolayout_id, params);
}

void C_Container::onHideLayout(ScriptObject *_layout) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_OBJECT(_layout);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), onhidelayout_id, params);
}

void C_Container::onShowLayout(ScriptObject *_layout) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_OBJECT(_layout);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), onshowlayout_id, params);
}

ScriptObject *C_Container::getLayout(const char *layout_id) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_STRING(layout_id);
  scriptVar *params[1] = {&a};
  return GET_SCRIPT_OBJECT(api->maki_callFunction(getScriptObject(), getlayout_id, params));
}

int C_Container::getNumLayouts() {
  ASSERT(inited);
  return GET_SCRIPT_INT(api->maki_callFunction(getScriptObject(), getnumlayouts_id, NULL));
}

ScriptObject *C_Container::enumLayout(int num) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_INT(num);
  scriptVar *params[1] = {&a};
  return GET_SCRIPT_OBJECT(api->maki_callFunction(getScriptObject(), enumlayout_id, params));
}

void C_Container::switchToLayout(ScriptObject *layout_id) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_OBJECT(layout_id);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), switchtolayout_id, params);
}

void C_Container::show() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), show_id, NULL);
}

void C_Container::hide() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), hide_id, NULL);
}

void C_Container::toggle() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), toggle_id, NULL);
}

int C_Container::isDynamic() {
  ASSERT(inited);
  return GET_SCRIPT_INT(api->maki_callFunction(getScriptObject(), isdynamic_id, NULL));
}

void C_Container::setName(const char *name) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_STRING(name);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), setname_id, params);
}

int C_Container::loaded=0;
int C_Container::onswitchtolayout_id=0;
int C_Container::onhidelayout_id=0;
int C_Container::onshowlayout_id=0;
int C_Container::getlayout_id=0;
int C_Container::getnumlayouts_id=0;
int C_Container::enumlayout_id=0;
int C_Container::switchtolayout_id=0;
int C_Container::show_id=0;
int C_Container::hide_id=0;
int C_Container::toggle_id=0;
int C_Container::isdynamic_id=0;
int C_Container::setname_id=0;
