/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __C_CONTAINER_H
#define __C_CONTAINER_H

#include "c_rootobj.h"

#define C_CONTAINER_PARENT C_RootObject

class COMEXP C_Container : public C_CONTAINER_PARENT {
  public:

  C_Container(ScriptObject *object);
  C_Container();
  virtual ~C_Container();

  virtual void C_hook(ScriptObject *o);

  ScriptObject *getScriptObject();

  virtual void onSwitchToLayout(ScriptObject *newlayout);
  virtual void onHideLayout(ScriptObject *_layout);
  virtual void onShowLayout(ScriptObject *_layout);
  virtual ScriptObject *getLayout(const char *layout_id);
  virtual int getNumLayouts();
  virtual ScriptObject *enumLayout(int num);
  virtual void switchToLayout(ScriptObject *layout_id);
  virtual void show();
  virtual void hide();
  virtual void toggle();
  virtual int isDynamic();
  virtual void setName(const char *name);

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int onswitchtolayout_id;
  static int onhidelayout_id;
  static int onshowlayout_id;
  static int getlayout_id;
  static int getnumlayouts_id;
  static int enumlayout_id;
  static int switchtolayout_id;
  static int show_id;
  static int hide_id;
  static int toggle_id;
  static int isdynamic_id;
  static int setname_id;
};

#endif
