/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __C_EDIT_H
#define __C_EDIT_H

#include "c_guiobject.h"

#define C_EDIT_PARENT C_GuiObject

class COMEXP C_Edit : public C_EDIT_PARENT {
  public:

  C_Edit(ScriptObject *object);
  C_Edit();
  virtual ~C_Edit();

  virtual void C_hook(ScriptObject *o);

  ScriptObject *getScriptObject();

  virtual void onEnter();
  virtual void onAbort();
  virtual void onIdleEditUpdate();
  virtual void onEditUpdate();
  virtual void setText(const char *txt);
  virtual void setAutoEnter(int onoff);
  virtual int getAutoEnter();
  virtual const char *getText();
  virtual void selectAll();
  virtual void enter();
  virtual void setIdleEnabled(int onoff);
  virtual int getIdleEnabled();

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int onenter_id;
  static int onabort_id;
  static int onidleeditupdate_id;
  static int oneditupdate_id;
  static int settext_id;
  static int setautoenter_id;
  static int getautoenter_id;
  static int gettext_id;
  static int selectall_id;
  static int enter_id;
  static int setidleenabled_id;
  static int getidleenabled_id;
};

#endif
