/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#include "../../../studio/api.h"
#include "c_grouplist.h"
#include "../objcontroller.h"

C_GroupList::C_GroupList(ScriptObject *object) : C_GuiObject(object) {
  ScriptObjectController *controller = object->vcpu_getController();
  if (!inited) {
    instantiate_id = api->maki_addDlfRef(controller, "instantiate", this);
    getnumitems_id = api->maki_addDlfRef(controller, "getNumItems", this);
    enumitem_id = api->maki_addDlfRef(controller, "enumItem", this);
    removeall_id = api->maki_addDlfRef(controller, "removeAll", this);
    scrolltopercent_id = api->maki_addDlfRef(controller, "scrollToPercent", this);
    setredraw_id = api->maki_addDlfRef(controller, "setRedraw", this);
    inited = 1;
  }
}

C_GroupList::~C_GroupList() {
  api->maki_remDlfRef(this);
}

ScriptObject *C_GroupList::instantiate(const char *group_id, int num_groups) {
  scriptVar a = MAKE_SCRIPT_STRING(group_id);
  scriptVar b = MAKE_SCRIPT_INT(num_groups);
  scriptVar *params[2] = {&a, &b};
  return GET_SCRIPT_OBJECT(api->maki_callFunction(getScriptObject(), instantiate_id, params));
}

int C_GroupList::getNumItems() {
  return GET_SCRIPT_INT(api->maki_callFunction(getScriptObject(), getnumitems_id, NULL));
}

ScriptObject *C_GroupList::enumItem(int num) {
  scriptVar a = MAKE_SCRIPT_INT(num);
  scriptVar *params[1] = {&a};
  return GET_SCRIPT_OBJECT(api->maki_callFunction(getScriptObject(), enumitem_id, params));
}

void C_GroupList::removeAll() {
  api->maki_callFunction(getScriptObject(), removeall_id, NULL);
}

void C_GroupList::scrollToPercent(int percent) {
  scriptVar a = MAKE_SCRIPT_INT(percent);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), scrolltopercent_id, params);
}

void C_GroupList::setRedraw(int redraw) {
  scriptVar a = MAKE_SCRIPT_INT(redraw);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), setredraw_id, params);
}

int C_GroupList::inited=0;
int C_GroupList::instantiate_id=0;
int C_GroupList::getnumitems_id=0;
int C_GroupList::enumitem_id=0;
int C_GroupList::removeall_id=0;
int C_GroupList::setredraw_id=0;
int C_GroupList::scrolltopercent_id=0;
