/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __C_LAYOUT_H
#define __C_LAYOUT_H

#include "c_group.h"

#define C_LAYOUT_PARENT C_Group

class COMEXP C_Layout : public C_LAYOUT_PARENT {
  public:

  C_Layout(ScriptObject *object);
  C_Layout();
  virtual ~C_Layout();

  virtual void C_hook(ScriptObject *o);

  ScriptObject *getScriptObject();

  virtual void onDock();
  virtual void onUndock();
  virtual void onScale(double newscalevalue);
  virtual double getScale();
  virtual void setScale(double scalevalue);
  virtual void setDesktopAlpha(int onoff);
  virtual ScriptObject *getContainer();
  virtual void center();

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int ondock_id;
  static int onundock_id;
  static int onscale_id;
  static int getscale_id;
  static int setscale_id;
  static int setdesktopalpha_id;
  static int getcontainer_id;
  static int center_id;
};

#endif
