/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#include "../../../studio/api.h"
#include "c_layout.h"
#include "../objcontroller.h"

C_Layout::C_Layout(ScriptObject *object) : C_Group(object) {
  inited = 0;
  C_hook(object);
}

C_Layout::C_Layout() {
  inited = 0;
}

void C_Layout::C_hook(ScriptObject *object) {
  ASSERT(!inited);
  ScriptObjectController *controller = object->vcpu_getController();
  obj = controller->cast(object, layoutGuid);
  if (obj != object && obj != NULL)
    controller = obj->vcpu_getController();
  else
    obj = NULL;

  if (!loaded) {
    loaded = 1;
    ondock_id = api->maki_addDlfRef(controller, "onDock", this);
    onundock_id = api->maki_addDlfRef(controller, "onUndock", this);
    onscale_id = api->maki_addDlfRef(controller, "onScale", this);
    getscale_id = api->maki_addDlfRef(controller, "getScale", this);
    setscale_id = api->maki_addDlfRef(controller, "setScale", this);
    setdesktopalpha_id = api->maki_addDlfRef(controller, "setDesktopAlpha", this);
    getcontainer_id = api->maki_addDlfRef(controller, "getContainer", this);
    center_id = api->maki_addDlfRef(controller, "center", this);
  }
  inited = 1;
}

C_Layout::~C_Layout() {
}

ScriptObject *C_Layout::getScriptObject() {
  if (obj != NULL) return obj;
  return C_LAYOUT_PARENT::getScriptObject();
}

void C_Layout::onDock() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), ondock_id, NULL);
}

void C_Layout::onUndock() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), onundock_id, NULL);
}

void C_Layout::onScale(double newscalevalue) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_DOUBLE(newscalevalue);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), onscale_id, params);
}

double C_Layout::getScale() {
  ASSERT(inited);
  return GET_SCRIPT_DOUBLE(api->maki_callFunction(getScriptObject(), getscale_id, NULL));
}

void C_Layout::setScale(double scalevalue) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_DOUBLE(scalevalue);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), setscale_id, params);
}

void C_Layout::setDesktopAlpha(int onoff) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_INT(onoff);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), setdesktopalpha_id, params);
}

ScriptObject *C_Layout::getContainer() {
  ASSERT(inited);
  return GET_SCRIPT_OBJECT(api->maki_callFunction(getScriptObject(), getcontainer_id, NULL));
}

void C_Layout::center() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), center_id, NULL);
}

int C_Layout::loaded=0;
int C_Layout::ondock_id=0;
int C_Layout::onundock_id=0;
int C_Layout::onscale_id=0;
int C_Layout::getscale_id=0;
int C_Layout::setscale_id=0;
int C_Layout::setdesktopalpha_id=0;
int C_Layout::getcontainer_id=0;
int C_Layout::center_id=0;
