/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#include "../../../studio/api.h"
#include "c_slider.h"
#include "../objcontroller.h"

C_Slider::C_Slider(ScriptObject *object) : C_GuiObject(object) {
  inited = 0;
  C_hook(object);
}

C_Slider::C_Slider() {
  inited = 0;
}

void C_Slider::C_hook(ScriptObject *object) {
  ASSERT(!inited);
  ScriptObjectController *controller = object->vcpu_getController();
  obj = controller->cast(object, sliderGuid);
  if (obj != object)
    controller = obj->vcpu_getController();
  else
    obj = NULL;

  if (!loaded) {
    loaded = 1;
    onsetposition_id = api->maki_addDlfRef(controller, "onSetPosition", this);
    onpostedposition_id = api->maki_addDlfRef(controller, "onPostedPosition", this);
    onsetfinalposition_id = api->maki_addDlfRef(controller, "onSetFinalPosition", this);
    setposition_id = api->maki_addDlfRef(controller, "setPosition", this);
    getposition_id = api->maki_addDlfRef(controller, "getPosition", this);
    lock_id = api->maki_addDlfRef(controller, "lock", this);
    unlock_id = api->maki_addDlfRef(controller, "unlock", this);
  }
  inited = 1;
}

C_Slider::~C_Slider() {
}

ScriptObject *C_Slider::getScriptObject() {
  if (obj != NULL) return obj;
  return C_SLIDER_PARENT::getScriptObject();
}

void C_Slider::onSetPosition(int newpos) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_INT(newpos);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), onsetposition_id, params);
}

void C_Slider::onPostedPosition(int newpos) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_INT(newpos);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), onpostedposition_id, params);
}

void C_Slider::onSetFinalPosition(int pos) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_INT(pos);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), onsetfinalposition_id, params);
}

void C_Slider::setPosition(int pos) {
  ASSERT(inited);
  scriptVar a = MAKE_SCRIPT_INT(pos);
  scriptVar *params[1] = {&a};
  api->maki_callFunction(getScriptObject(), setposition_id, params);
}

int C_Slider::getPosition() {
  ASSERT(inited);
  return GET_SCRIPT_INT(api->maki_callFunction(getScriptObject(), getposition_id, NULL));
}

void C_Slider::lock() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), lock_id, NULL);
}

void C_Slider::unlock() {
  ASSERT(inited);
  api->maki_callFunction(getScriptObject(), unlock_id, NULL);
}

int C_Slider::loaded=0;
int C_Slider::onsetposition_id=0;
int C_Slider::onpostedposition_id=0;
int C_Slider::onsetfinalposition_id=0;
int C_Slider::setposition_id=0;
int C_Slider::getposition_id=0;
int C_Slider::lock_id=0;
int C_Slider::unlock_id=0;
