/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __C_SLIDER_H
#define __C_SLIDER_H

#include "c_guiobject.h"

#define C_SLIDER_PARENT C_GuiObject

class COMEXP C_Slider : public C_SLIDER_PARENT {
  public:

  C_Slider(ScriptObject *object);
  C_Slider();
  virtual ~C_Slider();

  virtual void C_hook(ScriptObject *o);

  virtual ScriptObject *getScriptObject();

  virtual void onSetPosition(int newpos);
  virtual void onPostedPosition(int newpos);
  virtual void onSetFinalPosition(int pos);
  virtual void setPosition(int pos);
  virtual int getPosition();
  virtual void lock();
  virtual void unlock();

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int onsetposition_id;
  static int onpostedposition_id;
  static int onsetfinalposition_id;
  static int setposition_id;
  static int getposition_id;
  static int lock_id;
  static int unlock_id;
};

#endif
