// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Fri Oct  8 00:47:43 2004]
// 
// File        : api_pump.cpp
// Class       : api_pump
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#include "api_pump.h"


