// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Fri Oct  8 00:47:43 2004]
// 
// File        : api_pumpx.cpp
// Class       : api_pump
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------

#include "api_pumpx.h"
#include "api_pumpi.h"

#ifdef CBCLASS
#undef CBCLASS
#endif

#define CBCLASS api_pumpX
START_DISPATCH;
  CB(API_PUMP_ADDPUMPHANDLER, addPumpHandler);
  CB(API_PUMP_DEREGISTERSINK, deregisterSink);
  CB(API_PUMP_DEREGISTERSOURCE, deregisterSource);
  CB(API_PUMP_GETPUMPHANDLER, getPumpHandler);
  CB(API_PUMP_PULLDATA, pullData);
  CB(API_PUMP_PUSHDATA, pushData);
  CB(API_PUMP_REGISTERSINK, registerSink);
  CB(API_PUMP_REGISTERSOURCE, registerSource);
END_DISPATCH;
#undef CBCLASS

