// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Fri Oct  8 00:47:43 2004]
// 
// File        : api_pumpx.h
// Class       : api_pump
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------

#ifndef __API_PUMPX_H
#define __API_PUMPX_H

#include "api_pump.h"




// ----------------------------------------------------------------------------

class api_pumpX : public api_pump {
  protected:
    api_pumpX() {}
  public:
    virtual int addPumpHandler(PumpHandler *handler)=0;
    virtual int deregisterSink(DataSink *sink)=0;
    virtual int deregisterSource(DataSource *source)=0;
    virtual PumpHandler *getPumpHandler(PumpClass eclass)=0;
    virtual int pullData(GUID source, GUID puller, void *data, unsigned long sz, unsigned long *actual_sz)=0;
    virtual int pushData(GUID sink, GUID pusher, void *data, unsigned long sz)=0;
    virtual int registerSink(PumpClass eclass, DataSink *sink)=0;
    virtual int registerSource(PumpClass eclass, DataSource *source)=0;
  
  protected:
    RECVS_DISPATCH;
};

#endif // __API_PUMPX_H
